[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
raydium_swapper = "GqpnKEGRfwwisQxC8j9AHbtWf8BLzdo4mH3P5oJC7FiQ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
swap = "ts-node scripts/main.ts"
